import { formatDate, getWeekDays, isoDate, loadRecords, recordLowItems, seedDemoRecords } from "./app.js";

const root=document.querySelector("#recordsContent"); const modal=document.querySelector("#recordModal");
const records=seedDemoRecords(); const days=getWeekDays(); const today=isoDate(new Date());
let selected=days.some(day=>isoDate(day)===today)?today:isoDate(days[0]);
const dayNames=["Isnin","Selasa","Rabu","Khamis","Jumaat","Sabtu","Ahad"];
function esc(value=""){ return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }

function render(){ const weekRecords=records.filter(record=>days.some(day=>isoDate(day)===record.date)); const selectedRecords=records.filter(record=>record.date===selected); const doneDays=new Set(weekRecords.map(record=>record.date)).size;
  root.innerHTML=`<section class="records-heading"><p class="eyebrow">${formatDate(days[0],{day:"numeric",month:"short"})} — ${formatDate(days[6],{day:"numeric",month:"short",year:"numeric"})}</p><h1>Rekod minggu ini</h1><p>Tekan hari untuk melihat pemeriksaan yang telah dilakukan.</p></section><section class="record-stats"><div class="card mini-stat"><strong>${weekRecords.length}</strong><span>PEMERIKSAAN DIREKOD</span></div><div class="card mini-stat"><strong>${doneDays}/7</strong><span>HARI ADA REKOD</span></div></section><div class="day-tabs" role="tablist">${days.map((date,i)=>`<button class="day-tab ${selected===isoDate(date)?"active":""}" data-date="${isoDate(date)}" role="tab"><span>${dayNames[i]}</span><b>${date.getDate()}</b></button>`).join("")}</div><section class="record-list">${selectedRecords.length?selectedRecords.map(record=>recordCard(record)).join(""):`<div class="card empty-state"><span>▢</span><h3>Belum ada rekod</h3><p>Tiada pemeriksaan direkodkan untuk hari ini.</p></div>`}</section>`;
}
function recordCard(record){ const low=recordLowItems(record).length; return `<article class="card record-card"><span class="record-bag">${record.bag.replace("PHC ","PHC")}</span><div class="record-info"><strong>${esc(record.ppp)} · ${record.shift}</strong><small>${record.time} · ${low?`${low} item kurang`:"Semua lengkap"}</small></div><button class="view-button" data-record="${record.id}">LIHAT</button></article>`; }
function showRecord(record){ const low=recordLowItems(record); modal.hidden=false; modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="Butiran pemeriksaan"><div class="modal-handle"></div><div class="modal-head"><h2>Butiran pemeriksaan</h2><button class="modal-close" aria-label="Tutup">×</button></div><div class="detail-grid"><div class="detail-cell"><small>TARIKH</small><strong>${formatDate(new Date(`${record.date}T12:00:00`),{day:"numeric",month:"long",year:"numeric"})}</strong></div><div class="detail-cell"><small>MASA</small><strong>${record.time}</strong></div><div class="detail-cell"><small>BEG</small><strong>${record.bag}</strong></div><div class="detail-cell"><small>SHIFT</small><strong>${record.shift}</strong></div><div class="detail-cell"><small>PPP</small><strong>${esc(record.ppp)}</strong></div><div class="detail-cell"><small>STATUS</small><strong>${low.length?`${low} kurang`:"Lengkap"}</strong></div></div>${low.length?`<div class="restock-list"><p class="eyebrow">ITEM PERLU RESTOCK</p><ul>${low.map(item=>`<li>${esc(item.name)} — ${item.qty}/${item.standard}</li>`).join("")}</ul></div>`:""}<div class="prototype-note" style="margin-top:14px"><strong>Catatan</strong><p>${esc(record.notes||"Tiada catatan.")}</p></div></section>`; }
root.addEventListener("click",event=>{ const day=event.target.closest("[data-date]"); if(day){ selected=day.dataset.date; render(); return; } const button=event.target.closest("[data-record]"); if(button) showRecord(records.find(record=>record.id===button.dataset.record)); });
modal.addEventListener("click",event=>{ if(event.target===modal || event.target.closest(".modal-close")) modal.hidden=true; });
render();
