import { formatDate, getWeekDays, isoDate, loadRecords, reconcileRemoteRecords, recordLowItems } from "./app.js";
import { apiConfigured, fetchRecords } from "./api.js";

const root=document.querySelector("#recordsContent"); const modal=document.querySelector("#recordModal");
const days=getWeekDays(); const today=isoDate(new Date()); let records=loadRecords(); let loading=false; let notice="";
let selected=days.some(day=>isoDate(day)===today)?today:isoDate(days[0]);
const dayNames=["Isnin","Selasa","Rabu","Khamis","Jumaat","Sabtu","Ahad"];
function esc(value=""){ return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function recordTimestamp(record){ return new Date(record.savedAt||`${record.date}T${record.time||"00:00"}`).getTime()||0; }
function uniqueRecords(){ const seen=new Set(); return [...records].sort((a,b)=>recordTimestamp(b)-recordTimestamp(a)).filter(record=>{ const key=record.checkKey||`${record.date}|${record.bag}|${record.shift}`; if(seen.has(key)) return false; seen.add(key); return true; }); }

function render(){ const all=uniqueRecords(); const weekRecords=all.filter(record=>days.some(day=>isoDate(day)===record.date)); const selectedRecords=all.filter(record=>record.date===selected); const doneDays=new Set(weekRecords.map(record=>record.date)).size;
  root.innerHTML=`${notice?`<div class="connection-banner info"><strong>Status rekod</strong><span>${esc(notice)}</span></div>`:""}<section class="records-heading"><p class="eyebrow">${formatDate(days[0],{day:"numeric",month:"short"})} — ${formatDate(days[6],{day:"numeric",month:"short",year:"numeric"})}</p><h1>Rekod minggu ini</h1><p>Tekan hari untuk melihat pemeriksaan yang telah dilakukan.</p></section><section class="record-stats"><div class="card mini-stat"><strong>${weekRecords.length}</strong><span>PEMERIKSAAN DIREKOD</span></div><div class="card mini-stat"><strong>${doneDays}/7</strong><span>HARI ADA REKOD</span></div></section><div class="day-tabs" role="tablist">${days.map((date,i)=>`<button class="day-tab ${selected===isoDate(date)?"active":""}" data-date="${isoDate(date)}" role="tab"><span>${dayNames[i]}</span><b>${date.getDate()}</b></button>`).join("")}</div><section class="record-list">${loading?`<div class="card empty-state"><span>↻</span><h3>Memuatkan rekod</h3></div>`:selectedRecords.length?selectedRecords.map(record=>recordCard(record)).join(""):`<div class="card empty-state"><span>▢</span><h3>Belum ada rekod</h3><p>Tiada pemeriksaan direkodkan untuk hari ini.</p></div>`}</section>`;
}
function recordCard(record){ const low=recordLowItems(record).length; const pending=record.syncStatus==="PENDING"; return `<article class="card record-card"><span class="record-bag">${record.bag.replace("PHC ","PHC")}</span><div class="record-info"><strong>${esc(record.ppp)} · ${record.shift}</strong><small>${record.time} · ${low?`${low} item kurang`:"Semua lengkap"}${pending?" · menunggu sync":""}</small></div><button class="view-button" data-record="${record.id}">LIHAT</button></article>`; }
function showRecord(record){ if(!record) return; const low=recordLowItems(record); modal.hidden=false; modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="Butiran pemeriksaan"><div class="modal-handle"></div><div class="modal-head"><h2>Butiran pemeriksaan</h2><button class="modal-close" aria-label="Tutup">×</button></div><div class="detail-grid"><div class="detail-cell"><small>TARIKH</small><strong>${formatDate(new Date(`${record.date}T12:00:00`),{day:"numeric",month:"long",year:"numeric"})}</strong></div><div class="detail-cell"><small>MASA</small><strong>${record.time}</strong></div><div class="detail-cell"><small>BEG</small><strong>${record.bag}</strong></div><div class="detail-cell"><small>SHIFT</small><strong>${record.shift}</strong></div><div class="detail-cell"><small>PPP</small><strong>${esc(record.ppp)}</strong></div><div class="detail-cell"><small>STATUS</small><strong>${low.length?`${low.length} kurang`:"Lengkap"}</strong></div></div>${low.length?`<div class="restock-list"><p class="eyebrow">ITEM PERLU RESTOCK</p><ul>${low.map(item=>`<li>${esc(item.name)} — ${item.qty}/${item.standard}</li>`).join("")}</ul></div>`:""}<div class="record-note" style="margin-top:14px"><strong>Catatan</strong><p>${esc(record.notes||"Tiada catatan.")}</p></div></section>`; }

async function refresh(){ if(!apiConfigured()){ notice="Google Sheet belum disambungkan; rekod peranti dipaparkan."; render(); return; } loading=true; render(); try{ const from=isoDate(days[0]); const to=isoDate(days[6]); const remote=await fetchRecords(from,to); records=reconcileRemoteRecords(remote,from,to); notice=""; }catch(error){ notice=`Tidak dapat memuatkan Google Sheet: ${error.message}`; } loading=false; render(); }
root.addEventListener("click",event=>{ const day=event.target.closest("[data-date]"); if(day){ selected=day.dataset.date; render(); return; } const button=event.target.closest("[data-record]"); if(button) showRecord(uniqueRecords().find(record=>record.id===button.dataset.record)); });
modal.addEventListener("click",event=>{ if(event.target===modal || event.target.closest(".modal-close")) modal.hidden=true; });
render(); refresh();
